name: build-sdk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-php-sdk:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      PHP_SDK_REPO: github.com/DuC-cnZj/event-bus-php-sdk
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up php and composer
        uses: shivammathur/setup-php@2.3.0
        with:
          php-version: php7.4
          extensions: mbstring, intl
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug
          tools: php-cs-fixer, phpunit

      - name: Get dependencies
        run: |
          sudo apt-get install -y git
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protoc-3.13.0-linux-x86_64.zip
          sudo apt-get install unzip
          unzip protoc-3.13.0-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
          protoc --version
          git clone -b v1.33.2 --depth 1 https://github.com/grpc/grpc
          cd grpc
          git submodule update --init
          make grpc_php_plugin
          ls
          ls bins/
          ls bins/opt/
          ln -s  bins/opt/grpc_php_plugin /usr/local/bin/grpc_php_plugin

      - name: build php sdk
        run: |
          export PATH="$PATH:$HOME/.local/bin"
          protoc --version
          make build-php-sdk
          ls sdks/php

      - name: upload php sdk
        run: |
          cp sdks/.gitignore sdks/php/src/DucCnzj/
          cp sdks/README.md sdks/php/src/DucCnzj/
          cd sdks/php/src/DucCnzj
          MYPATH=$(pwd)
          cd /tmp
          git clone https://DuC-cnZj:${{ secrets.TOKEN }}@$PHP_SDK_REPO.git php-repo
          cd php-repo
          mv $MYPATH/* /tmp/php-repo/
          echo $GITHUB_SHA > sha.txt
          git config --local user.name "duc"
          git config --local user.email "1025434218@qq.com"
          git add .
          git commit -m "$GITHUB_SHA"
          git remote set-url --push origin https://DuC-cnZj:${{ secrets.TOKEN }}@$PHP_SDK_REPO.git
          git push -u origin master

#  build:
#    env:
#      PTOTO_REPO: github.com/DuC-cnZj/event-bus-proto
#    name: Build
#    runs-on: ubuntu-18.04
#    steps:
#      - name: setup
#        uses: actions/setup-go@v2
#        with:
#          go-version: ^1.15
#
#      - name: Check out code into the Go module directory
#        uses: actions/checkout@v2
#
#      - name: Get dependencies
#        run: |
#          sudo apt-get install -y git
#          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protoc-3.13.0-linux-x86_64.zip
#          sudo apt-get install unzip
#          unzip protoc-3.13.0-linux-x86_64.zip -d $HOME/.local
#          export PATH="$PATH:$HOME/.local/bin"
#          protoc --version
#          go install github.com/golang/protobuf/protoc-gen-go
#          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
#
#      - name: build protos
#        run: |
#          export PATH="$PATH:$HOME/.local/bin"
#          protoc --version
#          make build-protos
#
#      - name: upload protos
#        run: |
#          cd protos
#          MYPATH=$(pwd)
#          cd /tmp
#          git clone https://DuC-cnZj:${{ secrets.TOKEN }}@$PTOTO_REPO.git repo
#          cd repo
#          if [ ! -f "go.mod" ]; then go mod init $PTOTO_REPO;fi
#          mv $MYPATH/* /tmp/repo/
#          echo $GITHUB_SHA > sha.txt
#          git config --local user.name "duc"
#          git config --local user.email "1025434218@qq.com"
#          git add .
#          git commit -m "$GITHUB_SHA"
#          git remote set-url --push origin https://DuC-cnZj:${{ secrets.TOKEN }}@$PTOTO_REPO.git
#          git push -u origin master